version: '3'
services:
  apache2:
    build: apache2
    hostname: ##SITE_HOSTNAME##
    restart: always
    environment:
      LETS_ENCRYPT_EMAIL: "operations@enonic.com"
      LETS_ENCRYPT_DOMAINS: "##SITE_HOSTNAME##"
    ports:
      - "80:80"
      - "443:443"
      - "8001:8001"
    volumes:
      - etcletsencrypt:/etc/letsencrypt
      - varletsencrypt:/var/lib/letsencrypt
  exp:
    build: exp
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - repo:/enonic-xp/home/repo
      - work:/enonic-xp/home/work
      - snapshots:/enonic-xp/home/snapshots
    labels:
      io.enonic.backup.prescripts: "/usr/local/bin/backup.sh"
  mail:
    image: enoniccloud/postfix
    hostname: ##SITE_HOSTNAME##
    restart: always

volumes:
  repo:
  work:
  snapshots:
